language: php

addons:
  soundcloud:
    organization: "nebijokit"
    token:
      secure: SONAR_TOKEN

cache:
  directories:
    - $HOME/.composer/cache

php:
    - '7.2'

before_install: echo "extension = soap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - composer install --dev

script:
   - ./vendor/bin/phpspec run --format=dot
   - sonar-scanner
